name: AlphaCandy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pip
  - tk
  - tqdm
  - gym
  - pandas
  - scipy
  - pip:
      - tensorboard
      - tensorflow